name: tests

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18
          - 20

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true

      # Assuming the build artifacts are in the 'dist' folder
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages-${{ matrix.node-version }}
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download GitHub Pages artifact (Node 18)
        uses: actions/download-artifact@v2
        with:
          name: github-pages-18
          path: ./dist-18

      - name: Download GitHub Pages artifact (Node 20)
        uses: actions/download-artifact@v2
        with:
          name: github-pages-20
          path: ./dist-20

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-18 # Choose the appropriate directory to deploy
